### ISSUE TITLE
Doesn't set nice(2) value

### ISSUE THREAD

**Issue by devyn** [vityafx/thread-priority#20]
I was kind of expecting this crate on UNIX to call `nice(2)` in order to mark the thread as lower priority, but it doesn't. At least on Linux so far it seems I'm able to set the thread policy to Batch and that worked successfully, but Linux doesn't seem to do anything at all with the priority value; that's more for the realtime/deadline schedulers.

Am I looking for the wrong thing? I ended up just calling `libc::nice()` in my application.

**Comment by vityafx** [comment]
Hi @devyn! Thanks for a good question.
Seems like something I should consider working on here

**Comment by vityafx** [comment]
Just indicating that it is still in progress.

**Comment by vityafx** [comment]
Done in https://github.com/vityafx/thread-priority/pull/22

Please test it if you still use the crate.
