### ISSUE TITLE
Cannot build for cross-platform arm64-android (or any android)

### ISSUE THREAD

**Issue by mknnix** [vityafx/thread-priority#23]
Try to use "cross build" to aarch64-linux-android, and it fails due to compile errors, latest version v0.8.2 of crate thread_priority.
This process done(with unexpected) by github actions CI/CD, and uses latest version of crate cross. looks like only exception for android, it works fine on other systems. workflow yaml here https://github.com/mknnix/melminter-mod/actions/runs/2897593543/workflow

```
error[E0433]: failed to resolve: use of undeclared crate or module `unix`
   --> /cargo/registry/src/github.com-1ecc6299db9ec823/thread-priority-0.8.2/src/lib.rs:376:31
    |
376 |     pub fn policy<VALUE: Into<unix::ThreadSchedulePolicy>>(mut self, value: VALUE) -> Self {
    |                               ^^^^ use of undeclared crate or module `unix`

error[E0425]: cannot find function `set_current_thread_priority` in this scope
   --> /cargo/registry/src/github.com-1ecc6299db9ec823/thread-priority-0.8.2/src/lib.rs:264:9
    |
264 |         set_current_thread_priority(self)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^------
    |         |
    |         help: try calling `set_current_thread_priority` as a method: `self.set_current_thread_priority()`

error[E0412]: cannot find type `ThreadId` in this scope
   --> /cargo/registry/src/github.com-1ecc6299db9ec823/thread-priority-0.8.2/src/lib.rs:274:13
    |
274 |     pub id: ThreadId,
    |             ^^^^^^^^ not found in this scope
    |
help: consider importing this struct
    |
90  | use std::thread::ThreadId;
    |

error[E0425]: cannot find function `get_current_thread_priority` in this scope
   --> /cargo/registry/src/github.com-1ecc6299db9ec823/thread-priority-0.8.2/src/lib.rs:289:23
    |
289 |             priority: get_current_thread_priority()?,
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `thread_native_id` in this scope
   --> /cargo/registry/src/github.com-1ecc6299db9ec823/thread-priority-0.8.2/src/lib.rs:290:17
    |
290 |             id: thread_native_id(),
    |                 ^^^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `ThreadSchedulePolicy` in this scope
   --> /cargo/registry/src/github.com-1ecc6299db9ec823/thread-priority-0.8.2/src/lib.rs:327:20
    |
321 | pub struct ThreadBuilder {
    |                         - help: you might be missing a type parameter: `<ThreadSchedulePolicy>`
...
327 |     policy: Option<ThreadSchedulePolicy>,
    |                    ^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `set_thread_priority_and_policy` in this scope
   --> /cargo/registry/src/github.com-1ecc6299db9ec823/thread-priority-0.8.2/src/lib.rs:430:49
    |
430 |             (Some(priority), Some(policy)) => f(set_thread_priority_and_policy(
    |                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `thread_native_id` in this scope
   --> /cargo/registry/src/github.com-1ecc6299db9ec823/thread-priority-0.8.2/src/lib.rs:431:17
    |
431 |                 thread_native_id(),
    |                 ^^^^^^^^^^^^^^^^ not found in this scope

```

**Comment by vityafx** [comment]
Hi! Thanks much for your contribution! I'd like to help you with this issue but I have never built the library for android itself thinking it would work automagically with no changes, what doesn't seem to be the case. Can you suggest any more or less easy way to build the crate for android, perhaps, there is an android docker image there for building rust libraries already?

**Comment by mknnix** [comment]
docker image just a ubuntu linux with rustup toolchain installed and some build env (apt install);

also `use of undeclared crate or module 'unix'`: is this module only apply to few platforms only? is there can add android to it's `#[cfg]` syntax? ( https://docs.rs/thread-priority/latest/src/thread_priority/unix.rs.html#9 )

and then `cannot find function 'thread_native_id' in this scope` or `cannot find type 'ThreadId' in this scope` these is possible because `mod unix` does not import... (by removed uses `#[cfg(target_os =`), ok this crate looks like make use libc with linux/mac/bsd only, no contains android.

three, rust have one `target_os = android` and `#[cfg(any(` syntax. try uses it may helps.

**Comment by mknnix** [comment]
android "toybox" (it's alternative of busybox) implements that `nice` command, so may be android C library can be use as a normal linux kernel, you just need make it's operation looks like toybox-nice... but there a question is that crate `libc` can works on android? because android C library different than glibc (this case similar to bsd-style, maybe their has a specify for the android C lib?)

**Comment by mknnix** [comment]
> 

Ok for now Android build back again, but also other job for mac build fails... is other reason about to that? and mac target rollback-ing

Other systems no problem.

![tp-0 9 1-android-ok](https://user-images.githubusercontent.com/109908929/186126112-56fed5b5-cf9a-47d9-a364-75e81652f6c3.png)
![tp-9 0 1-mac-fails](https://user-images.githubusercontent.com/109908929/186126139-b83bc0c8-27e4-464a-bb3f-c6ebaa9ff0c1.png)

**Comment by vityafx** [comment]
Yes, sorry for that; that's some import issue, I thought I had already solved it. Will look later today.

**Comment by mknnix** [comment]
no problem prev version works fine for just mac

**Comment by vityafx** [comment]
Well, I am looking at the code right now and it should work fine. Also, the tests passed last time on macOS as well.

**Comment by mknnix** [comment]
Environment different or a out-of-sync between the published version and master? Both github actions are mac-runner and native compilation for mac (no cross); well I am looking. this should fixes [commit-1e19de](https://github.com/vityafx/thread-priority/commit/1e19de5e1564defbab732e903218463975a9b31a), but that change missing for cargo publish? check these cache/lock?

**Comment by mknnix** [comment]
Is macos really found SCHE_OTHER? It seems that cargo should not have not updated but may not exist in the macos environment "other"? or about to libc?
